### ISSUE TITLE
Establishing 501(c)(3) status

### ISSUE THREAD

**Issue by nedtwigg** [mytakedotorg/mytakedotorg#13]
I think we are either a [501(c)(3)](https://en.wikipedia.org/wiki/501(c)_organization#501.28c.29.283.29) for education or a [501(c)(4)](https://en.wikipedia.org/wiki/501(c)_organization#501.28c.29.284.29). 

501(c)(3) is the normal educational non-profit, and 501(c)(4) is a special political kind.  Hopefully our social entrepreneur friends can help us figure out which we should be.

**Comment by nedtwigg** [comment]
Since we're not backing a specific candidate, we are a 501(c)(3).  Also, turns out to be inexpensive, and it helps a lot with taxes for the folks who are donating to us.

Next step is to decide what state to incorporate in.  Delaware is my gut...

**Comment by WebsByTodd** [comment]
Why Delaware?

**Comment by nedtwigg** [comment]
When it comes to for-profit startups, VC's will only invest in Delaware corps, because their lawyers already know the Delaware law.  The first step for lots of companies taking VC for the first time is reincorporating as a Delware corp.

It might be different for non-profits.

**Comment by nedtwigg** [comment]
This is also a blocker for getting a bank account for taking donations.  Once we have an organization, we can get a bank account for it.

**Comment by hattersv** [comment]
Yes I am fine with that in June.   Will also try to see what state is best for nonprofits as that seems to be a question.

**Comment by hattersv** [comment]
OK, from a very quick google research effort (more to be done), it turns out there are quite a few different models across the various states.  Delaware is still in the 'least regulated' column, however there is a caveat: " If you're looking for the least amount of regulation, then Delaware, Nevada, Wisconsin, and Arizona may be the states for you. Please note, in Delaware, non-profit corporations are governed by the same provisions that govern for profit corporations".  I am not exactly sure what that means.

Many states follow the Model Non-Profit Corporation Act, which appears to provide more protections than the less regulated ones.    Once there is income, some states have mandatory stringent non-profit corporate audits, which would be good to avoid, as they are apparently expensive, but they have different requirements dependent on gross income.  Some start at $25,000 and others are up at $500,000 or a million.  ((1) California, Connecticut, Hawaii, Arkansas, Georgia, Florida, Kansas, Maine, Maryland, Massachusetts, Michigan, Minnesota, Mississippi, New Hampshire, New Mexico, New York, New Jersey, North Carolina, Pennsylvania, Rhode Island, Tennessee, Virginia, Washington, and Wisconsin.). South Carolina is NOT one of these, Cal and Mass are.... just FYI :-)

If the plan is to eventually fund-raise in all 50 states, then we need to register in at least 39 of those states (I found some seemingly conflicting info on the number).  Note that these rules were somewhat  losely followed in the past with on-line fund-raising, though they are beginning to get actually implemented.

Source:  Quora, National Council on Non-profits, and the Chronicle of Philanthropy

**Comment by hattersv** [comment]
HI Ned and Todd.  We are meeting at 1 today, is that what you have in your calendar?  Proposed agenda or at least items to cover:

Update on what V has discovered and done so far.
What Ned and Todd's thoughts on incorporation are
Decide what state to incorporate in.
Determine next steps and necessary timelines.

**Comment by hattersv** [comment]
Hi again - if that time isn't what you expected it could be that I didn't actually send that message, other than in my head (:-(... I can't find it.  So if necessary we can set up another time.  If that is the case I can use more time to get more info anyway.

**Comment by hattersv** [comment]
I have several files that I want to share and will attach them here.  If there is a better way to do this let me know.... I don't know if we have the ability to view shared files when we talk.  These are the very preliminary files adapted from my friends documents that were prepared for Massachusetts.  These would need to be adopted for what every state you incorporate in.  I also include a checklist for setting up a 501 C3 and, as I have mentioned, it is not for the faint of heart! :-).   Looks like it loaded as a .png file but I don't know if the content actually loaded, I'll have a look once I save.

[MytakesCaseForSupportDRAFT2017.docx](https://github.com/nedtwigg/mytake/files/1153349/MytakesCaseForSupportDRAFT2017.docx)
[MyTakeBylawsDRAFT.docx](https://github.com/nedtwigg/mytake/files/1153350/MyTakeBylawsDRAFT.docx)

![image](https://user-images.githubusercontent.com/28243995/28279052-3aee8ff6-6aed-11e7-9dc5-f3c713314a43.png)

**Comment by hattersv** [comment]
https://www.score.org/blog/non-profit-startup-checklist

**Comment by nedtwigg** [comment]
Task items that came out of todays meeting:

### Victoria

- [ ] Find incorporation fees for CA and DE
- [ ] Find donation reqs for CA and MA

### Ned

- [ ] Long term budget
- [ ] Long term timeline

### Todd

- [ ] Build mytake ;-)

**Comment by hattersv** [comment]
Registration costs are minimal.  I include the links to the details for your reference.

California:  Here is the link to the information 
 https://www.harborcompliance.com/information/how-to-start-a-non-profit-organization-in-california

Costs:
![ca costs](https://user-images.githubusercontent.com/28243995/28789387-40cad69e-75f3-11e7-8037-a89b590f4212.png

DE:  https://www.harborcompliance.com/information/how-to-start-a-non-profit-organization-in-delaware

Costs:
![de costs](https://user-images.githubusercontent.com/28243995/28789572-e0c4b6f6-75f3-11e7-8c45-cdee1b0dbb07.png)

Donation requirements, but remember if you don't actively solicit these then as long as they aren't huge you don't need to register.:  

CA:  $25 filing fee, some counties require additional filing fees.  Must register within 30 days of receiving assets that are held in a trust.

![ca donation](https://user-images.githubusercontent.com/28243995/28789978-5f958c20-75f5-11e7-882b-d3cf08633f7d.png

Mass:
 
$100 plus $50-$1000 scale of fees depending upon gross support and revenue.
![ma donation a](https://user-images.githubusercontent.com/28243995/28790206-23166fca-75f6-11e7-9752-1701cbc79b3a.png)
![ma donation b](https://user-images.githubusercontent.com/28243995/28790211-29a1e356-75f6-11e7-8ee2-140fe2a8de51.png)

**Comment by nedtwigg** [comment]
Thanks a ton Victoria.

Watsi was the first nonprofit funded by Y Combinator.  Turns out that they are registered in CA, not DE, and all their documents are available online ([search here for Watsi] if you're curious).  I'm going to use them as my template for everything.

I'm going to start filling out the paperwork for a 501(c)(3) based in CA by following the instructions that Victoria found.  I plan on filing it all myself, rather than paying a service.

I'll send all docs to you before I submit them.

**Comment by nedtwigg** [comment]
(# = the number as listed on [this page](https://www.harborcompliance.com/information/how-to-start-a-non-profit-organization-in-california), just for reference)

- [ ] File ARTS-PF-501(c)(3) with California Sec State (#5)
- [ ] File SI-100 with California Sec State (#6)
- [ ] Get EIN by filing SS-4 (#7)
- [ ] Write bylaws and conflicts of interest policy
- [ ] Hold our first board meeting
    - [ ] Approve bylaws
    - [ ] Approve conflict of interest policy
    - [ ] Elect directors
    - [ ] Appoint officers
    - [ ] Approve resolutions (e.g. opening bank account)
    - [ ] Record all of the above in the meeting minutes
- [ ] Get california state tax ID
- [ ] Apply for 501(c)(3) with IRS via 1023-EZ
- [ ] Get CA tax-exempt with 3500A
- [ ] Register for donations in CA with CT-1

Burning through these is at the top of my todo.

**Comment by nedtwigg** [comment]
From the 1023 app, Part VIII 4b

> Do you or will you have written or oral contracts with any individuals or organizations to raise funds for you?  If “Yes,” describe these activities. Include all revenue and expenses from these activities and state who conducts them. Revenue and expenses should be provided for the time periods specified in Part IX, Financial Data. Also, attach a copy of any contracts or agreements.

For now, we have checked no on this box.  I can imagine a case where some other nonprofit says "Hey guys!  Go to mytake.org and click donate, cuz they're awesome!", but I don't think that would count for this question.  What kind of hypothetical contracts can you imagine we might want to make in the future, @hattersv?

**Comment by nedtwigg** [comment]
Just to keep this up-to-date, our 501(c)(3) status is currently pending.

**Comment by nedtwigg** [comment]
We got approved a long time ago, huzzah!
