### ISSUE TITLE
Changes required to publish farewell addresses

### ISSUE THREAD

**Issue by nedtwigg** [mytakedotorg/mytakedotorg#434]
- [ ] Add support for video speeches https://github.com/mytakedotorg/mtdo/issues/430
- [ ] Add support for radio speeches https://github.com/mytakedotorg/mtdo/issues/431
  - might not be on critical path, depending on https://github.com/mytakedotorg/us-presidential-farewell-addresses/issues/1
- [ ] Add support for text-only speeches https://github.com/mytakedotorg/mtdo/issues/432
- [ ] Add support for multiple factsets https://github.com/mytakedotorg/mtdo/issues/433
